### ISSUE TITLE
Edit group size and acceptable group sum range

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#10]
For now, groups are mostly small (though some reach impressive sizes), and "de" is set to a very narrow range, making grouping fairly difficult.

I'd like to try different configurations, which means forcing the program to make groups at least 5 localities big, or perhaps even 10.. and set the acceptable "de" for the group to a wider range (-3 to +3) for example.  

This could be implented through a textbox on the main window.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/805b54ae-1986-465a-baf1-19ce16d25d60)

**Comment by remidelattre** [comment]
Yes, this is exactly how I envisioned it.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/3c0e0653-55dc-4b4b-8713-4a269636d13e)

**Comment by JamesBremner** [comment]
v0.0.6

**Comment by JamesBremner** [comment]
This was assigned to you in test 2 days ago.

From your comments in #12 it seems that you have been using this feature without much trouble.

Is there any particular reason that this issue has not been closed?

**Comment by remidelattre** [comment]
Was keeping this open but ended up discussing the matters in another issue. Closing it now, thanks !

**Comment by JamesBremner** [comment]
> Was keeping this open ...

It is important to maintain a clear distinction between testing an implemented feature and discussing possible future enhancements.

Allowing  feature testing to be delayed by 'nice to have' discussions is one of the ways that software development becomes doomed to failure..
