### ISSUE TITLE
Increasing group sum range while maintaining fixed group size worsens coverage

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#12]
I have yet to compare the results of this algorithm to handmade groups for _de_ between -0,5 and 0,5 in REG93.  However, within [min.de : -0,5, max. de : 0,5, min. group size 5] parameters, this algorithm covers 43.5% of localities in the region. Our simulated annealing algorithm covers 45.1 % in 24 hours and 190000 iterations.

I do wonder about larger groups. While trying to generate bigger groups, I've noticed allowing a greater range for "de" does not seem to dramatically alter the results. I'd assume allowing groups to have values between -100 and 0 would lead to an almost complete coverage of the region, despite asking the algorithm to create groups containing no less than 27 localities. Yet, with those kind of parameters, only a fifth of localities are grouped in REG93. With 20 localities minimum and "de" between -100 and 0, a third of the localities are grouped. This is especially surprising because the groups themselves do not stray away very far from zero, despite the sample being overly negative. Is this due to the algorithm design ?

Pictured below is an example of this issue. Using the algorithm with the parameters _de between -100 and 0, min group size = 26_, I've noticed the results were not as good as they were on _de_ values closer to zero. In a few minutes, I was able to generate handmade groups that fit the criterion and that should have been generated by the algorithm. Notably, handmade group 3 contained 195 localities, and I could have kept going.

![image](https://github.com/JamesBremner/so77307162/assets/148571442/38b5ae2d-2545-4f3f-8f10-f187f314645e)

**Comment by remidelattre** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/148571442/90c27997-d48b-40d1-8851-92b05d793c54)

Results yielded this morning with a strange phenomenon - increasing _"de"_ margin does not generate more groups

**Comment by remidelattre** [comment]
It has been brought to my attention that line 127 might be the culprit when using wider and more negative ranges. The condition according to which localities should be ignored when they take group sum further away from zero works when you tend towards zero, but doesnt with other ranges.

**Comment by JamesBremner** [comment]
Guessing you mean this line:

https://github.com/JamesBremner/so77307162/blob/8e442f2ff4ea1158c6eebe64751e5f242da4fdb2/src/cGrouper.cpp#L157-L159

>  doesnt with other ranges.

Please clarify this.  An example of a range where it doesn't work would help me to understand your point.

**Comment by JamesBremner** [comment]
Please try with the range -100 to 0.0001

**Comment by remidelattre** [comment]
With -100 to 0.0001, for REG=93, min. size 26, the results are 240 of 1043 localities covered, which is almost the same as what I got using 0.5 instead of 0.0001 (235).

**Comment by JamesBremner** [comment]
So, there is still a problem?

> Handmade group 3, for example, contains 195 localities and a de value of -33.

You are reporting that a group you expected was not present in the output?  Since the groups are generated from localities selected in order that they are read in, you cannot expect any particular group to be generated.

**Comment by JamesBremner** [comment]
I see that you have a minimun groups size of 26.  That is very big!  I imagine that the ungrouped localities belong to potential groups that were rejected because they were too small.  If you want to assign the maximum number of localities to groups, you will need to specify a large range AND a small or zero minimum group size.

**Comment by remidelattre** [comment]
Looking at the map, there was room for many more groups with 26+ localities that would also feature sums between -100 and 0. This is evidenced by the fact that I was able to make those groups. Therefore, I dont think the algorithm rejected those groups because they were too small. It was possible, even, to make groups of 200+ localities while keeping "de" within -100 and 0. 

Obviously, asking the algorithm to generate bigger groups while maintaining the same range for acceptable "de" will mean less coverage. But if the acceptable range for "de" also widens, grouping should be easier.

**Comment by JamesBremner** [comment]
> Obviously, asking the algorithm to generate bigger groups while maintaining the same range for acceptable "de" will mean less coverage.

Exactly.

Try reducing your minimum group size.

**Comment by remidelattre** [comment]
This does not explain why increasing "de" range while maintaining the same group size worsens coverage though. 

To expand on this logic, if min.de was set to -3502 (which corresponds to the total deficit for this region), then one group should be produced : the region itself (without a few islands, of course). This is because the algorithm should try to minimize ungrouped localities and maximize group size.

**Comment by JamesBremner** [comment]
> increasing "de" range while maintaining the same group size worsens coverage though.

In general that shouldn't happen, I don't think.  Perhaps some larger groups 'steal' localities from later groups, preventing them from being formed?

I will take a look at that when I have finished working on #11

**Comment by JamesBremner** [comment]
Here is some results on the localities assigned to groups in region 93 for varying minimum group size and group sum ranges

![image](https://github.com/JamesBremner/so77307162/assets/2046227/68ce4b6a-ad6a-407c-8b5e-fa38123894c3)

Conclusions:

- Increasing the range accepted **increases** the coverage, up to about +/-25.  After that the coverage remains the same or even declines slightly.  This makes sense because increasing the range allowed will allow more groups to be accepted.
- Increasing the minimum group size **decreases** the coverage.  This makes sense because increasing the minimum size prevents smaller groups from being accepted.

**Comment by remidelattre** [comment]
With 3/-3, minimum group size 10 : 424/946 in 39 groups
With 5/-5, minimum group size 10 : 394/945 in 38 groups

Therefore, increasing the range does not necessarity increases the coverage. Increasing the range to the point that any group works as long as it is bigger than N localities does not yield results. No group can be made with 100+ localities, regardless of range. This is surprising because one could easily draw a path between a hundred adjacent localities. Thus, the current function does not seem to minimize the number of ungrouped localities. Assuming no "de" constraint, the biggest and only group should be the region itself, regardless of the starting location in the region as long as that starting location is connected to the mainland. Perhaps because the function tends to ignore localities that take the sum away from zero while the dataset is mostly comprised of negative values, it is impossible to group every adjacent locality regardless of range. When given huge ranges, the algorithm will still try to make the groups as close to zero as possible, when it should make use of that range to cover more localities. This formula can compete with a simulated annealing algorithm when asked to create -0.5/0.5 groups with no size limitation, but will fall behind as range increases because it favours localities for which de >0 in an overwhelmingly negative dataset. Is that correct ?

**Comment by JamesBremner** [comment]
> With 3/-3, minimum group size 10

group size 10 is too big to give optimum coverage.  My results indicate that a group size of 5 or less does significantly better

In the real world, I would imagine than trying to organize 10 localities to share their land takes would be very frustrating.  Here in Canada we have 10 provinces.  It is quite impossible to get them all to agree on anything!

**Comment by remidelattre** [comment]
This is true : the more little the groups, the better we share. The best solution, actually, is to pool every excedentary "de" value in a given region and distribute them so that we reduce the amount of localities with a "de" deficit. But this is far too ambitious to actually be applied in the real world. Besides, imagine having to reduce your land consumption more because a locality 200 kilometers away was not very savvy. We still calculated the formula, but eh. 

A bit less optimal is adjacent grouping. With less localities involved in each group, the problem is..politics. Less environmental friendly municipalities might feel singled out. Bigger groups offset individual responsibilities. Therefore, so far, bigger groups have been applied. Not the most optimal distribution, but a politically sound one. With this search for an adjacency algorithm, we're trying to find a compromise : we would not want ungrouped localities (they'd feel left out) but we should also avoid groups that bear the whole regional burden of land take reduction. We should also have groups that avoid wasting surpluses. Hence the question : how to have everyone in a group, groups that have same-ish land take constraints, and groups that have a normal size (ie more than 20) ? We figured, as long as we get coverage and range as parameters, we'd probably be able to find the best compromise.

**Comment by remidelattre** [comment]
Thus, the question would be : assuming eveyrone has to be in groups of at least 20 adjacent localities, how do we avoid extreme variations in "de" deficits between the groups ? If we change the minimum group size, how does that change ? Of course, we could manually make groups, but this is very error prone, as my video displays.

**Comment by JamesBremner** [comment]
>  assuming everyone has to be in groups of at least 20 adjacent localities,

Why would you assume that?  The coverage would be terrible and the implementation would be almost impossible.

>  how do we avoid extreme variations in "de" deficits between the groups ?

Reduce the range of the group sum.  This will also give you better coverage.

**Comment by remidelattre** [comment]
> Why would you assume that? The coverage would be terrible and the implementation would be almost impossible.

I assume that because this is how we're handling it right now. Pre-existing groups of 26 localities on average are being used to mutualize land take rights. However, as I'm trying to demonstrate, this is not a great solution, because this means excedentary "de" is being wasted, and on the contrary, some groups are starving for more "de". If we have to keep groups roughly the same size, we could change their borders to make the process better. Let's ask an algorithm to generate those groups was my idea. Of course, no one will reach zero, but we can at least prevent some very difficult situations in which groups have de=-100, for example, while others have de > 100.

> Reduce the range of the group sum.

I would, but that means incomplete coverage. If every group has a negative "de", yet everyone is in a group and we cant do much better to reduce variations in "de" between groups, we've got the best compromise.

**Comment by JamesBremner** [comment]
> Pre-existing groups of 26 localities on average are being used to mutualize land take rights. However, as I'm trying to demonstrate, this is not a great solution

Exactly!  It is demonstrated by

![image](https://github.com/JamesBremner/so77307162/assets/2046227/68ce4b6a-ad6a-407c-8b5e-fa38123894c3)

A group size of 25 ( ~26 ) shows that the number of localities assigned to a group is more than halved compared to a more sensible groups size of 5.  QED

**Comment by JamesBremner** [comment]
> If every group has a negative "de", yet everyone is in a group and we cant do much more to reduce variations in "de" between groups, we've got ourselves the best compromise.

Have you tried asymmetric ranges?  Say -10 to +2.

**Comment by remidelattre** [comment]
With this formula, for sure., the number of localities is halved or even worse, because the formula won't create groups that stray too far away from zero. However, if you manually make groups, you can absolutely have groups of 30 localities as long as you accept having negative "de" & inequal de betwenn groups (see my map for reference, or see the dataset). At worst, you might have 29 ungrouped localities. My hope was that inputing a wide and negative range in this algorithm would reflect that. After all, if there are almost no constraints to a group sum, many combinations are possible that involve every locality. I was looking to find a balance between "de" range constraints and group size, i.e find groups of suitable size that would roughly have the same sum, although negative.

**Comment by JamesBremner** [comment]
**Suggestion**:  Use a two pass implementation.  Run the algorithm with the optimal parameters (Range +/- 5, Size 5 ) then run it again with relaxed parameters ( say range +/- 25, size 2 ) to "mop up" the remaining unassigned localities.

**Comment by remidelattre** [comment]
Interesting suggestion. I'll make sure to try that tommorow. We also thought about running the two algorithms in succession with the same constraints.

**Comment by JamesBremner** [comment]
>  I'll make sure to try that tommorow. 

It requires some new code to implement.

**Comment by remidelattre** [comment]
In the meantime, I'll manually make groups for REG93 that : 

- Contain on average 26 localities
- Have roughly similar "de" sums, hopefully as high as possible on average
- Reduce the amount of ungrouped localities

This will give me a benchmark that I can test against algorithms.

**Comment by JamesBremner** [comment]
If you want  me to implement the two pass suggestion, open a new issue and assign it to me.

**Comment by remidelattre** [comment]
This is my attempt at manually generating groups with a minimum size of **32 localities**. The resulting « de » range is **-95 to -459.** I forced myself to cover every locality. I did not necessarily maximize group size, but I used a minimum group size of 32. Lastly, I tried (and failed) to have roughly equivalent sums for every group. I attempted to reach an optimum which can be measured by the following formula :

> (Region deficit / number of localities) * min.group size
> (3500/943) * 32 = 118

Given no adjacency constraint, 32 locality groups should have on average a deficit of -118. This is obvioulsy unreachable, but we can compare our combination with this optimum and use this as a metric for comparison. This formula helps us figuring out the best possible balance between group deficits, given no adjacency constraint.
 
![image](https://github.com/JamesBremner/so77307162/assets/148571442/df1b28a7-8914-428f-abe7-9a8ca5273282)

This handmade grouping is clearly lackluster : an algorithm would definitely do a better job. My average deficit is 269. My median is 289. Another way to assess performance is to see how well we’ve balanced deficits. With a deficit of approximately 3500 and 943 localities, each locality should bear on average a deficit of 3.711. With my grouping, however, Group 1 localities end up with an average deficit of 0.33 while Group 13 localities end up with an average deficit of 14. Besides, it took me about an hour and a half. I should have reduced the amount of localities with deficits in group 1 and have group 1 eat group 12. But this is easier said once the grouping is over. 

We can now use two metrics to review grouping performance within the same coverage and group size parameters. Those metrics can help us choose the best formula. Obviously, no algorithm can yield the optimum results because those are calculated without adjacency constraints. The point is to try to get closer. 

As of now, these results are impossible to compare to the algorithm’s output because :
-	The algorithm won’t accept a range between two negative values
-	The algorithm won’t attempt to maximize the number of grouped localities
-	The algorithm will always avoid localities that take the sum farther away from zero

The following modifications to the formula could, according to me allow the algorithm to beat my performance (i.e reach an average deficit closer to 118 within the same parameters than I did, both in terms of average and median) :

-	Force the algorithm to cover every locality. Let it dictate « de » range based on the required coverage and on the required group size
-	Adjust the formula based on the required group range. If we’re trying to have every locality in a group and if those localities amount to a deficit of -3522, avoiding localities which take us farther from zero won’t work. Instead, if « de » range is -100 to 0, perhaps avoiding localities that take us farther from -50 could be an interesting start.

**Comment by JamesBremner** [comment]
> Force the algorithm to cover every locality. Let it dictate « de » range based on the required coverage and on the required group size

Please open a new issue for this and clarify how you want this to work.

**Comment by JamesBremner** [comment]
I am still waiting for your response to my two pass suggestion https://github.com/JamesBremner/so77307162/issues/12#issuecomment-1780094441

In the meantime I have coded a quick test of its effectiveness.  It offers a significant improvement to the coverage.

![image](https://github.com/JamesBremner/so77307162/assets/2046227/7beebd66-2d30-433d-b6cf-6f06f3ac210d)

**Comment by remidelattre** [comment]
This is interesting. I figured forcing the algorithm to generate 100% coverage would negate the relevancy this feature, but when using the function to generate zero-sum groups, two passes seems like an important improvement. Will close this issue and open a new one related to this feature.
