### ISSUE TITLE
Design algorithm to cover an entire dataset with groups

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#14]
**1. Purpose of the current formula**

We’ve made some important progress. Notably, we can now determine the maximum amount , size and coverage of groups if we’re tying to generate zero-sum adjacent groups. However, using multiple criteria to rate an algorithm output is a tough process, because :
-	The problem is NP-complete
-	This would involve weighting every criterion (importance of group size vs importance of coverage vs importance of average group deficit)
-	The current formula is perfect when it comes to zero-sum groups, but will falter when faced with overly negative values.

**2. Forcing 100% coverage and overriding predefined "de" margins** 

To make the issue simpler, we could add an option to cover every locality with groups, within a given dataset. This means that instead of predifining an acceptable « de » range, we’d let the algorithm create groups of N+ adjacent localities so that they end up with roughly equivalent « de ». When attempting to generate groups covering every locality, users should not be allowed to input a specific « de » range, because this would face the algorithm with an unsolvable problem. However, they should be able to tweak minimum group size so that we can document the effects of group size on the sharing process. Instead of using a predefined acceptable « de » range, the algorithm should try to balance « de » between grouped localities. Regardless of the distribution of values in the dataset, groups would be generated. 

**3. Problem formulation and output evaluation**

The problem formulation would be the following : assuming we need every locality in groups of minimum N localities, how can we distribute « de » so that every group has – roughly – the same ratio between group sum and group size ?

 
![image](https://github.com/JamesBremner/so77307162/assets/148571442/9b1a9866-da2b-4fc0-9873-83d823de4d89)

I’m opened to suggestions, but I think a good metric to assess an output’s quality would be to look at the variation between highest and lowest group ratios. Here, output 1 wins because localities are closer to have equal « de ».

**4. Dealing with absolute and relative islands**

A line should be implented to deal with islands, because those will prevent 100% coverage. Therefore, islands should be removed prior to the grouping process. In the same vein, localities that are adjacent to less neighbours than the min. group size should be removed. In REG93, this is the case for the exclave highlighted below which would create issues as soon as we want 100% coverage with groups bigger than 4 localities.

![image](https://github.com/JamesBremner/so77307162/assets/148571442/16ab6852-870d-423e-9c8a-7cdba66baad1)

I would then manually reintegrate those localities within groups after the output is generated. They are rare enough, so it's fairly quick.

**Comment by JamesBremner** [comment]
> islands should be removed prior to the grouping process.

In graph theory, an "island" is called a "component".  The PathFinder graph theory library has a method for finding the components of a graph ( https://github.com/JamesBremner/PathFinder/wiki/Components-or-Cliques ) so this will be easy to implement.

In detail, all the components of the graph are found, and all but the largest 'removed'.

I am uncertain what you intend by 'remove'.  It seems a shame just to ignore them.  Suggestion:  Every component smaller the the minimum group size parameters should be made into its own group.  Components larger than that should have the the assignment algorithm run separately on them.

If this sounds good to you, please open a new issue, say 'Handle components', and assign it to me.

**Comment by JamesBremner** [comment]
This is still a question!

>instead of predifining an acceptable « de » range, we’d let the algorithm create groups of N+ adjacent localities so that they end up with roughly equivalent « de ». 

Please clarify how you intend this to be achieved.  

( You do not just 'let' an algorithm do something.  You have to specify step by step how it is to be done.

![image](https://github.com/JamesBremner/so77307162/assets/2046227/57f58a94-9711-43ed-9db8-e4e2e71eff81)

**Comment by JamesBremner** [comment]
**Suggestion 1:**

I expect that the ungrouped localities will be mostly disconnected from each other because their neighbors _have_ been assigned to groups.  So we could try forcing any that **are** connected to each other into groups, without regard to the acceptable de sums or group size.  We would allow even single localities, that are isolated because ALL their neighbors have bee assigned, to be in a 'group' of one locality.

**Suggestion 2:**

```
- LOOP U over unassigned localities
    -   LOOP A over adjacent assigned localities to U
          - Add U to adjacent group that moves the de sum of the group the least distance away from zero.
```

**Comment by remidelattre** [comment]
Could we use the existing function but instead of seeking to make groups close to zero, try instead to define a target group deficit based on minimum group size ? For example, assuming 943 localities with a deficit of 3500 and groups of 32, the target group deficit would be -109, and the target locality deficit -3.711. To avoid creating ungrouped unaccessible localities is indeed the hardest part. However, if we accept the results when the number of ungrouped localities at the end of the process is less than the minimum size of a group, do you think it would take many iterations to yield an acceptable result ? If thirty localities remain ungrouped, yet 95% of the region is comprised of groups with roughly equivalent sizes and deficits, all it takes is a bit of manual post-processing to assign the remaining localities to the groups where they less raise intra and inter cluster variance. I guess this is is similar to your second suggestion.

What about - and this may sound like a silly idea - generating millions of groups of a given size within a region, and pick the one iteration which minimizes intra and inter cluster variance ? Sounds absolutely barbarian, but running this on a dedicated computer for a while could end up yielding a result.

**Comment by JamesBremner** [comment]
"try instead to define a target group deficit"

What does this mean? The target group deficit range is defined.  Who or what is doing the 'trying'.  The algorithm?

" the target locality deficit "

What does this mean?  The locality deficit is defined in the input.  It cannot be changed.

**Comment by remidelattre** [comment]
During the clustering process, your objective is to form groups in such a way that each group's total deficit (the sum of deficits of all communes within that group) is as close as possible to the target deficit value we set for a given min. group size and region deficit (109). This means that the algorithm will aim to minimize the difference between the actual total deficit of each group and the target deficit.

 Achieving the target group deficit means balancing the trade-off between the size of the group (32 localities) and their total deficit. The algorithm will try to form groups that are as close as possible to the target deficit while ensuring that each group contains the specified number of communes.

 The optimization process involves minimizing the difference (variance) between the actual deficits of communes within the same group. This helps in creating homogeneous groups in terms of deficits.

**Comment by JamesBremner** [comment]
>  the target value is not zero anymore

This is a major change to the problem statement!!!!!!!!!

Problem statement:

> A group of localities must touch and have a sum of values close to zero

If you want to make this change, open a new issue and assign it to me.

**Comment by remidelattre** [comment]
I understand. I actually believed the value would not change the problem statement, because the aim remains to group localities around a specific value, wether that be 0, 5, -100. Could you explain why this involves major changes ? I'm curious to know more.

**Comment by JamesBremner** [comment]
>  I actually believed the value would not change the problem statement

Have you read the problem statement recently?  https://github.com/JamesBremner/so77307162#problem

**Comment by JamesBremner** [comment]
> Could you explain why this involves major changes ?

Any changes to a problem statement is a big deal.  The problem statement underlies an entire project.  Frequent changes, undermining confidence in the problem statement, is a good way to doom a project to failure.

**Comment by remidelattre** [comment]
Yes, I know the problem statement states that groups should be close to zero. However, I believed that selecting another target would not fundamentally change the function for grouping. The assignement is different, the way localities are explored can remain the same. If I'm incorrect, please explain.

**Comment by JamesBremner** [comment]
I call this algorithm guided breadth first search.  The guidance will need to be changed.  The next locality to be visited during the search will often be different.

As usual, the coding work will be less than all the back and forth discussing it. Can we stop chatting about this and make a decision, please?

**Comment by remidelattre** [comment]
Sure, let's try to implement a dynamic target in an attempt to cover the whole dataset with groups. I think this issue suffices in presenting the problem.

**Comment by JamesBremner** [comment]
>  the target value is ... is dynamic depending on the sample. 

Obviously, this cannot be implemented until we change the group definition.

Once that it done, you will need to describe how the "target value" is to be calculated from the input.  It would be a good idea to start a new issue to discuss the details of this calculation.
