### ISSUE TITLE
Handle components

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#15]
- Check graph for multiple components. 
- Assign the localities in any component that is smaller than the minimum group size to its own group.
- Apply the assignment algorithm ( modified BFS ) separately to each remaining component.

Note: a component is a subset of the nodes in a graph where every node in a subset is reachable from every other node in the same subset and by no nodes in the other subset.  If all the nodes in a graph are reachable form each other, then the graph has one component.

**Comment by JamesBremner** [comment]
" I think this implementation would be worth it."

OK.  Please remember to assign an enhancement issue to me when you have decided you want it to be implemented

**Comment by JamesBremner** [comment]
I have edited the initial comment to clarify what will be implemented.  Please check that this matches your requirements.

**Comment by remidelattre** [comment]
This matches the requirements, thanks.

**Comment by JamesBremner** [comment]
The island in region 93 is the first assigned group, even though it exceeds the specified maximum de sum

```
Sum -5 to 5, Min. Size 5
497 of 946 localities assigned to 87 groups.

============
84053 1.296293366 84097 2.231346688 84138 3.959005417 84150 1.158613508 sum 8.64526
============
04001 -3.801613008 04046 -1.377181693 04122 1.773550306 04070 8.017084361 04108 -1.327775998 sum 3.28406
...
```

**Comment by JamesBremner** [comment]
v0.0.10

**Comment by JamesBremner** [comment]
I will make the component handling optional, default off.

![image](https://github.com/JamesBremner/so77307162/assets/2046227/f7de2e26-5d55-41b2-9dea-a52b82e864e3)

( Notice that while I was in the GUI code, I added the group sum target on the assumption that at some point you will decide to do this )

**Comment by JamesBremner** [comment]
v0.0.11
