### ISSUE TITLE
Two pass implementation to maximize coverage

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#16]
In circumstances where no condition states that the coverage ought to be 100%, using a two pass implementation appears to maximize coverage. This would involve running the algorithm with the parameters set by the user first, and then running it again with relaxed parameters in an attempt to group unassigned localities.

**Comment by JamesBremner** [comment]
Again, please remember to assign an enhancement issue to me if you want me to implement it.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/b2f6158e-7247-4902-bcba-e347adf7a459)

**Comment by JamesBremner** [comment]
v0.0.8
