### ISSUE TITLE
Grouping ALL regionsmake component detection very, very slow

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#17]
![image](https://github.com/JamesBremner/so77307162/assets/148571442/57e5d776-f955-4b92-9da4-9be57fbd79af)

Upon inputing those parameters, Depaver will freeze.

**Comment by JamesBremner** [comment]
Reproducible.

**Comment by JamesBremner** [comment]
Which region(s) were your grouping?

Grouping region 93 is successful.  Grouping ALL regions hangs in the component detector.

**Workaround**:  Group one region at a time.

**Comment by JamesBremner** [comment]
The problem is that the component detector is very slow when asked to process 34,000 localities.  It is not really hanging. just working away at the problem.

How useful do you find the component handling ( #15 )?  I am thinking that we could back out component handling or make it optional so that processing all regions could be grouped in a reasonable amount of time

**Comment by remidelattre** [comment]
Do you think it's that slow ? I guess I have a different view on what's slow and what's not, having ran the same python script for the last 72 hours or so :D

On a more serious note, for testing purposes, I agree that the faster we generate results, the better. We can probably keep component handling for later, as the lack of it does not significantly alter results.

**Comment by JamesBremner** [comment]
Note for future:

When posting a bug report, especially involving the application "hanging" or "crashing", it saves a lot of time if the console log is included.  It looks like this:

```
finished 1st pass through input
finished reading 946 localities
Detecting components
component found
component found
2 components detected
Assign Pass 1
87 groups assigned
```

**Comment by JamesBremner** [comment]
> We can probably keep component handling for later, as the lack of it does not significantly alter results.

Please open an issue for this.  Alternatively, reopen #15

**Comment by JamesBremner** [comment]
Wondering why you are keeping this one open.
