### ISSUE TITLE
Calculation of non-zero target group size

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#19]
target group size = (Average locality deficit in a given region * Desired group size)

For REG93, that would be 

```
(-3500/943) * 32 = -118.750
```

**Comment by JamesBremner** [comment]
This will have to wait until the group definition is changed to allow non-zero target for the group sums.

**Comment by JamesBremner** [comment]
For simplicity, I will add a display of the average locality deficit.

Usage: 

- Run assignment with any parameters
- Note average deficit, divide by number localities ( also displayed ) and multiply by desired group size
- Enter calculated target and run assignment

**Comment by remidelattre** [comment]
This is a great idea :) . Avoids having to open the sample in a spreadsheet app and calculate it everytime.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/df7617e8-e7be-40c3-a0e2-7e9d72d049ab)
