### ISSUE TITLE
Change group definition to allow non zero group sum targets

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#20]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/b12687d1-42c3-4a55-bd89-2cc9c4c16798)

This requires a change to the problem statement and the implementation of the guided breadth first algorithm.

**Comment by JamesBremner** [comment]
I have changed the problem statement https://github.com/JamesBremner/so77307162#problem

**Comment by JamesBremner** [comment]
I do not think it makes a lot of sense to have a different target sun for pass 2, so I will remove that.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/955c6b46-4d11-474d-b615-d562f6d03e7c)

**Comment by remidelattre** [comment]
Interesting, it will resort less to actually using the minimum size. I see fairly big groups. For reference, with min. size 20, range -150 to -118, we've got 63% and counting with simulated annealing. Though that does take some time :D

**Comment by JamesBremner** [comment]
v0.0.11
