### ISSUE TITLE
Add unassigned localities to best adjacent group

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#21]
As per #18, an inner loop could improve coverage and work within the context of grouping for values other than 0.

- LOOP U over unassigned localities
    -   LOOP A over adjacent assigned localities to U
          - Add U to adjacent group that moves the de sum of the group the least distance away from target sum

**Comment by JamesBremner** [comment]
Average locality deficit -3.68182

Sum -22 to -18, Min. Size 5

946 of 946 localities assigned to 63 groups.

 Group size: min 5 av 6.34921 max 15      Group deficit:  min -22.3703 av -20.289 max -18.1042

```
============
84018 -3.020023941 84079 1.108881531 84075 -0.549648069 84072 -6.595199808 84070 -10.40870801 84066 -4.064215212 84150 1.158613508 sum -22.3703
============
04004 -4.701654056 04166 -6.165652354 04230 28.82751951 04189 -1.933016885 04143 -0.90772212 04094 -33.84247635 sum -18.723
============
04124 2.436997072 04157 -7.059854713 04172 -1.435391592 83014 -9.015429534 04176 -2.166478961 83015 -1.734889031 sum -18.975
```

...

**Comment by JamesBremner** [comment]
v0.1.0

**Comment by JamesBremner** [comment]
Updated the algorithm description https://github.com/JamesBremner/so77307162#algorithm

**Comment by remidelattre** [comment]
This is impressive, you've managed to group every locality ! Can't wait to test this when I get a chance. Thank you :)

**Comment by remidelattre** [comment]
If you wanted to try with the following range : -158 to -118
Min. group size = 20 
Which parameters would you input ? I've been trying this but the app freezes.
![image](https://github.com/JamesBremner/so77307162/assets/148571442/8f35d9db-bf4f-4e27-ad82-9b9f18705125)

**Comment by remidelattre** [comment]
If you were to try the following parameters : 
Range -150 to -118
Min. group size 20
How would you input the parameters ? I've been trying this but it crashes. 
 
![image](https://github.com/JamesBremner/so77307162/assets/148571442/ccd88a5a-5c7a-496c-b639-50de48bf80fe)

**Comment by JamesBremner** [comment]
The range is input using deltas ( as the prompts say, and the same as it was in v0.0 ) not the absolute values.

So:

-118
-32
1

**Comment by remidelattre** [comment]
Strange, inputting those will crash the app, with min. group size 20. Would copy console but it closed too.

**Comment by JamesBremner** [comment]
A group size of 20 is bad idea.  You will get poor initial coverage, so the adding of unassigned localities will not work very well.

Remember this:

![image](https://github.com/JamesBremner/so77307162/assets/2046227/68ce4b6a-ad6a-407c-8b5e-fa38123894c3)

If you have found some input that crashes the application you should open a bug issue.

**Comment by remidelattre** [comment]
I see. I'm inputting those values because I can compare them to results produced by SA.

**Comment by JamesBremner** [comment]
I suggest you compare the results from a run with the optimum parameters.  Comparing the results of a run using parameters that you know give poor results is hardly a fair comparison.

**Comment by remidelattre** [comment]
SA is so slow I only have data for specific ranges and values. I thought a fair comparison would be to input the exact same parameters in both apps to see which yields the best coverage.

**Comment by JamesBremner** [comment]
The algorithms work quite differently.  So, naturally, they do best with with different parameters.

**Comment by JamesBremner** [comment]
A parameter is a way of tuning an algorithm to produce the result that you want.  It is not a wish that the algorithm will respect and obey, magically producing the result you want merely because you asked nicely.

This is one of the reasons that time is always an issue when designing algorithms.  The algorithm must run fast enough that you can run it multiple times with different parameters to find the optimal combination.  If you cannot produce a graph like this

![image](https://github.com/JamesBremner/so77307162/assets/2046227/e5a82d2b-d73e-498c-9505-ffce438ce781)

then you will never be able to get the best out of your algorithm

**Comment by remidelattre** [comment]
Yeah, we'll produce a graph like this eventually. We're storing data for both programs and I will organize it. We have a few months, and it takes about 4 days to get the best out of one SA test. Thank you for the suggestion !

**Comment by remidelattre** [comment]
Closing this one as I've got the chance to test it with the latest version :)
