### ISSUE TITLE
Handle one group created.

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#22]
![image](https://github.com/JamesBremner/so77307162/assets/148571442/40d110f8-032c-409f-ae68-bf3426dbdb7e)

The app will freeze. Clicking on it will crash it and the console too.

**Comment by JamesBremner** [comment]
**Cause:**  Only one group is created.

```
Average locality deficit -3.68182
Sum -150 to -117, Min. Size 20
946 of 946 localities assigned to 1 groups.
 Group size: min 946 av 946 max 946      Group deficit:  min -3501.21 av -3501.21 max -3501.21
```

**Workaround:**  Use optimal parameters

**Fix:**  I assumed you would always get multiple groups ( you do if you use sensible parameters )  An vector must be going out of bounds somewhere.  I will run it under the debugger and add a check where needed

**Comment by JamesBremner** [comment]
I cannot reproduce this.  

When I use those parameters the algorithm produce just one group, but it does not crash nor freeze.

![image](https://github.com/JamesBremner/so77307162/assets/2046227/153568d4-3f61-4f98-b584-3b9a1e8e3151)

Can you test this again, please.

**Comment by remidelattre** [comment]
[Here it is](https://www.youtube.com/watch?v=IK2I5hTAnpI)

**Comment by JamesBremner** [comment]
That goes past too fast.  Did you remember to select the region first?

**Comment by remidelattre** [comment]
This is a case of me being used to editing settings before choosing region. Case closed, thank you :D

**Comment by JamesBremner** [comment]
2nd occurrence  https://github.com/JamesBremner/so77307162/issues/17#issuecomment-1782863117

I will combine the selection of the included regions and the algorithm editor into one
