### ISSUE TITLE
Combine region selection & parameter editor

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#23]
Usability

https://github.com/JamesBremner/so77307162/issues/17#issuecomment-1782863117

and

https://github.com/JamesBremner/so77307162/issues/22#issuecomment-1783916217

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/c35431d4-3f6e-4aee-9686-578fdbfb24a5)

**Comment by JamesBremner** [comment]
Why have you closed this!  You have not tested it.  I haven't even released it.

I have been admiring how quickly you test and close issues after I release their implementation.  Now I am am suspecting your  speed is because you do not bother to test them!!!!!!

What is going on?

**Comment by JamesBremner** [comment]
If an issue is not assigned to you, then leave it alone.

**Comment by JamesBremner** [comment]
You should be getting an email when an issue is assigned to you.  However, if you are like me you get dozens of emails each day, then it is easy to miss an assignment.  So, I recommend keeping this page ( https://github.com/issues/assigned ) open in a browser tab.  This lists all the issues currently assigned to you in every github repository.  To know when this page needs to be refreshed keep an eye on the notification icon, which appears at the top right on every page

![image](https://github.com/JamesBremner/so77307162/assets/2046227/efc85649-7cd5-4bbf-b1f9-919ae1827c35)

A blue dot will appear on this when something has happened that needs your attention.

By the way, I would really appreciate if you would remember to assign issues to me when you want me to do something.  I have asked you to do this many times, since it makes it a lot easier for me to respond to requests coming in from different repos.

**Comment by JamesBremner** [comment]
I have assigned this to you in test.

So **now** you can test v0.1.1

**Comment by remidelattre** [comment]
Tested. This makes it more intuitive, I'd say. Thank you !
