### ISSUE TITLE
Result Image

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#3]
This was posted in the wrong issue

> I have a question for you : in the example picture you provided, it seems like the groups are interconnected, 

![image](https://github.com/JamesBremner/so77307162/assets/2046227/f9b9b06d-6d20-4cd9-9a9a-5421d79b0025)

**Comment by JamesBremner** [comment]
> it seems like the groups are interconnected,

Yes.

From your post to stackoverflow

> The municipalities must be contiguous, 

( You seem to use "group" and "municipality" to mean the same thing )

So the groups MUST be connected.  

In the image the red localities are assigned to the first group, the blue localities are in the second group.  Take a look at the text output from the app to get the details.

**Comment by JamesBremner** [comment]
Please note the first line in the algorithm description:

 - Convert input to a graph data structure with vertices representing localities and edges connecting localities that share an edge

**Comment by remidelattre** [comment]
A group is a set of localitlies (i.e 84001, 84002, 84003, 84004, 84005). That would be group 1. 
Here's a rundown of the group-making process where I try to make a group by hand and explain the logic behind my choices in terms of pathing.
https://youtu.be/_Of0RGLQ4tI
This does not adress the geometry problem you mentioned. Unfortunately, I was hoping to solve this with QGIS. With QGIS, the fact that there are 3 coordinates does not seem to hamper adjacency detection.

**Comment by JamesBremner** [comment]
Your question was about the image my app outputs

> I have a question for you : in the example picture you provided, it seems like the groups are interconnected,

Have I clarified how to understand the image?  do you have any more questions about the image?

**Comment by remidelattre** [comment]
Yes, I get it now, thanks. Having verticles is very interesting because it shows the interactions. With what i show in the video, i cant really have verticles shown, though i could display the tree edges and the back edges. I had trouble understanding because I did not clarify the difference between groups and municipalities/localities. My video shows the difference : a locality/municipality is one single polygon, while a group is the perimeter within which those polygons are contained.

**Comment by JamesBremner** [comment]
> Yes, I get it now, thanks

Seems like you can now close this issue.
