### ISSUE TITLE
Groups, layout display is blank at user's site

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#6]
> At this point, starter.exe is a greyish window

Oops, this is a known bug which I forgot about.

Work around: run the program a second time.

**Comment by JamesBremner** [comment]
v0.0.2

**Comment by remidelattre** [comment]
latest version will now show two menus : groups, text and : groups, layout. _"Groups, text"_ shows the values for every group. _"Groups, window"_ remains empty.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/3dca5b13-91fa-4934-9c22-e09d429ac01d)

**Comment by remidelattre** [comment]
![22101901](https://github.com/JamesBremner/so77307162/assets/148571442/6218e014-97b8-4a97-bf10-aec8c0b45930)

**Comment by JamesBremner** [comment]
> "Groups, window" remains empty.

I assume you mean "groups, layout"

Please post the contents of your temp folder.  It should look like this

![image](https://github.com/JamesBremner/so77307162/assets/2046227/aabd87f8-d8ff-4a73-aba9-b9b796cfbad9)

You will need to replace "james" with your own user name.

**Comment by remidelattre** [comment]
![22101907](https://github.com/JamesBremner/so77307162/assets/148571442/5c705244-c184-432a-8b67-3908a5f66998)
I have .gdot, many tmp files, but no sample.png

**Comment by JamesBremner** [comment]
I can see the dot file, but not the png file.

Best guess, you do not have graphViz installed.

You can check like this:

```
>dot -V
dot - graphviz version 2.47.1 (20210417.1919)
```

You can download from https://graphviz.org/download/#windows

**Comment by remidelattre** [comment]
fixed it, thank you very much. closing issue.
![22101943](https://github.com/JamesBremner/so77307162/assets/148571442/980ffc8c-e5d5-4db1-b075-64d301c37ddd)
