### ISSUE TITLE
Group localities in a subset of regions

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#7]
Posted in #1 

> 
> Added a ( column ) containing regional codes. This allows us to create .csv filles contaning a smaller amount of localities while running the tests within perimeters that are actually relevant to the problem the algorithm intends to solve. If you watched my video, you can see me reducing the sample at the start. This the same principle, except with actually relevant perimeters.
> 
> We may need to adress the fact that, using this method, we're asking the program to consider adjacencies that won't exist in the smaller files. Perhaps this would require ignoring localities that the program can't find or cleaning the .csv beforehand.
>

**Comment by JamesBremner** [comment]
> Perhaps this would require ignoring localities that the program can't find

This seems the correct approach.  

Let me know if you want me to implement this ( the easiest way to do that is to assign this issue to me. )

**Comment by remidelattre** [comment]
Yeah, or even simpler to program - perhaps - ask the user to provide the .csv by loading it ? Otherwise, yeah, options would be great. I'll look at how you programmed the reader for the adjacency matrix.

**Comment by JamesBremner** [comment]
Please remember: if you want me to implement something, assign the issue to me.  Then it will get a high priority in my todo list.

**Comment by JamesBremner** [comment]
**To select which regions to be grouped**

 - Select menu item `File |  Regions` to group
 - Enter required regions using space separated list e.g. "84 32"  To group all, set list to blank.
 - You will be prompted to select the adjacency list file input.  Use same one for all regions

**To select which region group is displayed in GUI**

- Select menu item `View | Region`
- Enter region ID, one only.

**Comment by JamesBremner** [comment]
v0.0.4

**Comment by remidelattre** [comment]
Will run tests based on this new .exe tommorrow. In the snapshot of the results you provided, I saw that for one group, "de" was 0.779. Is there any way for the user to define a range for the target "de" ? I'd like to try with different ranges to see how that affects group-making. In the same vein, I'd like to edit minimum group-size. As you can see, the total sum for the localities is negative, so the "zero-sum" game is impossible to attain. The spirit is to reach a compromise. Admittedly, having bigger groups makes it harder, but this could be compensated by accepting a wider range for "de". 

Also, for your information, this algorithm has to do with policies related to land take in France. I cannot share too many details because this is an ongoing paper : I am a PHD student in France. We will make sure to credit you if we get the chance to publish an article related to this issue later this year and I'll send you the work. Regardless of what algorithm we end up choosing, the speed at which this processes groups is far better than what we've had so far using Python.

**Comment by JamesBremner** [comment]
>  Is there any way for the user to define a range for the target "de" ?

As always, if you want an enhancement then open a new issue, describe the feature you want to add, and assign the issue to me.

**Comment by JamesBremner** [comment]
Thank you for giving me some information.  The purpose of all this has been a mystery to me.  I will open a new issue to discuss this.

**Comment by JamesBremner** [comment]
>  I saw that for one group, "de" was 0.779. Is there any way for the user to define a range for the target "de" 

This seems to be a bug.  Currently, acceptable groups are supposed to have a sum in the range -0.5 to 0.5

**Comment by JamesBremner** [comment]
> the speed at which this processes groups is far better than what we've had so far using Python.

In general, C++ apps run 50 to 100 time faster then Python.  They are also a lot easier to debug, so development goes more quickly since developer spends a lot less time tracking down typos, etc.

**Comment by JamesBremner** [comment]
>  I was not able to adjust group size.

Please read https://github.com/JamesBremner/so77307162/issues/7#issuecomment-1775925448

**Comment by JamesBremner** [comment]
> To access the "View, region" option, should I first input a regional file ?

There is no need for 'regional files''.  The "View, region"" selects which regions to view - it does not effect what regions are grouped which is controlled by the "File, Regions"  option.  Please read https://github.com/JamesBremner/so77307162/issues/7#issuecomment-1775847473

**Comment by JamesBremner** [comment]
> typing a regional code like 93 wont display results.

That is strange.  This works fine here

![image](https://github.com/JamesBremner/so77307162/assets/2046227/e0d148cb-af8a-4001-8d20-cace24f0c436)


Does it work for other regions?

Are you using the input file https://github.com/JamesBremner/so77307162/blob/main/dat/test1/adjacencies.txt

Please test this again and post a screenshot with the input box.

**Comment by JamesBremner** [comment]
> Is there any way to set minimum group size and tweak "de" values ?

Please read https://github.com/JamesBremner/so77307162/issues/7#issuecomment-1775925448

**Comment by JamesBremner** [comment]
General comment:  Your written English is excellent :-)

However, you often pack several topics into one paragraph.  Please could you, at least, split each topic into its own paragraph.  It would make my job easier and reduce the chance that I miss something.

**Comment by remidelattre** [comment]
Thanks ! It works with every region, I was just misunderstanding it.
I'm now trying to convert this
19011 0.610256165 19216 1.738685316 19025 1.9898 19243 0.920506943 19059 -9.572711804 19121 1.112489515 19230 -4.755553384 19144 0.946025236 19254 1.340955765 24397 1.673371238 19094 3.890560049 sum -0.105615

Into something that would look like :  

insee | de | group | groupsize
-- | -- | -- | --
19011 | 0.61 | 1 | 11
19216 | 1.738 | 1 | 11

groups would be randomly numbered, ungrouped would be -1.
