### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#8]
from #7 

> 
 this algorithm seeking process has to do with policies related to land take in France. I cannot share too many details because this is an ongoing paper : I am a PHD student in France. We will make sure to credit you if we get the chance to publish an article related to this issue later this year and I'll send you the work. Regardless of what algorithm we end up choosing, the speed at which this processes groups is far better than what we've had so far using Python.

**Comment by JamesBremner** [comment]
Thanks.

I do not know what 'land take' means.

**Comment by remidelattre** [comment]
Land take is the conversion of natural land to sealed soil as a result of urbanization. An european policy aims to halt land take by reducing it by 50% by 2030. This data is a series of surplus/deficits measured in hectares based on localities needs for the next decade. Surplus means the locality has excedentary hectares compared to the 50%, deficits means they have less. Localities can share hectares, and the algorithm does it.

**Comment by remidelattre** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/148571442/9d2a77fc-1728-4017-8198-28ab6fb30b2b)
not sure where to post it, but this is a snippet of our spiraled annealing working. It's pretty slow but I hope to be able to compare outputs soon :)

**Comment by JamesBremner** [comment]
> Land take is ...

Thanks.  That makes a lot of sense.

Neat project.

**Comment by JamesBremner** [comment]
The purpose is to reduce the amount of natural land taken by urbanization by 50%.

Sounds like a great idea!  

I wonder what the 50% means.  Say a locality has a de value of 0.  This means, AFAIK, that its planned land take from now till 2030 is 50% of something.  What is the something?

**Comment by JamesBremner** [comment]
Makes me think of the Joni Mitchell song 'Big Yellow Taxi'

They paved paradise, put up a parking lot
With a pink hotel, a boutique, and a swingin' hot spot
Don't it always seem to go
That you don't know what you've got 'til it's gone
They paved paradise, put up a parking lot
(Ooh, bop-bop-bop-bop, ooh, bop-bop-bop-bop)
They took all the trees put 'em in a tree museum
And they charged the people a dollar an' a half just to see 'em
Don't it always seem to go
That you don't know what you've got 'til it's gone
They paved paradise, put up a parking lot
(Ooh, bop-bop-bop-bop, ooh, bop-bop-bop-bop)
Hey farmer, farmer put away that DDT now
Give me spots on my apples, but leave me the birds and the bees
Please
Don't it always seem to go
That you don't know what you've got 'til it's gone
They paved paradise, put up a parking lot
(Ooh, bop-bop-bop-bop, ooh, bop-bop-bop-bop)
Late last night I heard the screen door slam
And a big yellow taxi took away my old man
Don't it always seem to go
That you don't know what you've got 'til it's gone
They paved paradise, put up a parking lot (ooh, bop-bop-bop-bop)
I said don't it always seem to go
That you don't know what you've got 'til it's gone
They paved paradise, put up a parking lot (ooh, bop-bop-bop-bop)
They paved paradise, put up a parking lot (ooh, bop-bop-bop-bop)
They paved paradise
Put up a parking lot

https://music.youtube.com/watch?v=NhxZ8ok3Z2o

**Comment by remidelattre** [comment]
Using cadastral files, the government is able to tell how much land a municipality has consumed over the previous decade.
Using a simulation, we calculate how much a municipality actually needs.
"De" is the result of this operation.

This song is indeed quite relevant. You can imagine this law does not make everyone happy ! But for now, it stands.

**Comment by JamesBremner** [comment]
I do not understand how that works, but I don't need all the details.  Enough that I know what this is all about in general terms.  Thanks.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/2046227/b9b7efe5-10a4-44f7-88ed-f00b098c5be6)
