### ISSUE TITLE
Groups accepted outside acceptable range

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#9]
Reported in #7

![image](https://github.com/JamesBremner/so77307162/assets/2046227/bcfee7c8-b049-4ee0-9383-278432563f04)

**Comment by JamesBremner** [comment]
This is reproducible

![image](https://github.com/JamesBremner/so77307162/assets/2046227/b0216e76-153a-499f-96b6-76f1b496e075)

**Comment by JamesBremner** [comment]
Cause: confusion about integer and floating point in calculation absolute value of group sum

**Comment by JamesBremner** [comment]
v0.0.5

**Comment by remidelattre** [comment]
With this version, groups will now be within -0,5 to 0,5.
